services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=my_database'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
    ports:
      - '5672:5672'
